/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gdm;


import gdm.entidades.clases.Agradecimiento;
import gdm.entidades.clases.Egreso;
import gdm.entidades.clases.Escuela;
import gdm.entidades.clases.Especialidad;
import gdm.entidades.clases.Metal;
import gdm.entidades.clases.Modelo;
import java.awt.Cursor;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.Clases.AgradecimientoNegocio;
import negocio.Clases.EgresoNegocio;
import negocio.Clases.EscuelaNegocio;
import negocio.Clases.EspecialidadNegocio;
import negocio.Clases.MetalNegocio;
import negocio.Clases.ModeloNegocio;
/**
 *
 * @author Chuy
 */
public class JDialogConfiguraciones extends javax.swing.JDialog {
    private List<Escuela> escuelas;   
    private List<Especialidad> especialidades;   
    private List<Modelo> modelos;   
    private List<Metal> metales;   
    private List<Egreso> egresos;
    private List<Agradecimiento> agradecimientos;
    /**
     * Creates new form JDialogConfiguraciones
     */
    public JDialogConfiguraciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarEscuelas();      
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelEscuela = new javax.swing.JPanel();
        jPanelEscuelas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEscuelas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarEscuela = new javax.swing.JButton();
        btnEditarEscuela = new javax.swing.JButton();
        btnEliminarEscuela = new javax.swing.JButton();
        txtEscuela = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnBuscar1 = new javax.swing.JButton();
        jPanelCarrera = new javax.swing.JPanel();
        jPanelCarreras = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEspecialidad = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarCarrera = new javax.swing.JButton();
        btnEditarCarrera = new javax.swing.JButton();
        btnEliminarCarrera = new javax.swing.JButton();
        txtEspecialidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jPanelMetal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMetales = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnAgregarMetales = new javax.swing.JButton();
        btnEditarMetales = new javax.swing.JButton();
        btnEliminarMetales = new javax.swing.JButton();
        jPanelEgresos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblEgresos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnEditarEgreso = new javax.swing.JButton();
        btnAgregarEgreso = new javax.swing.JButton();
        btnEliminarEgreso = new javax.swing.JButton();
        jPanelAgradecimientos = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblAgradecimientos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanelModelos = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblModelos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnAgregar1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelEscuelas.setBackground(new java.awt.Color(248, 255, 255));
        jPanelEscuelas.setMaximumSize(new java.awt.Dimension(750, 550));
        jPanelEscuelas.setMinimumSize(new java.awt.Dimension(750, 550));

        tblEscuelas.getTableHeader().setFont(new java.awt.Font("Euphemia", 0, 18));
        tblEscuelas.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        tblEscuelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Escuela", "Ciudad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEscuelas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblEscuelas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblEscuelas.setRowHeight(23);
        tblEscuelas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblEscuelas);
        if (tblEscuelas.getColumnModel().getColumnCount() > 0) {
            tblEscuelas.getColumnModel().getColumn(0).setMinWidth(0);
            tblEscuelas.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblEscuelas.getColumnModel().getColumn(0).setMaxWidth(0);
            tblEscuelas.getColumnModel().getColumn(1).setMinWidth(250);
            tblEscuelas.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblEscuelas.getColumnModel().getColumn(1).setMaxWidth(250);
            tblEscuelas.getColumnModel().getColumn(2).setMinWidth(200);
            tblEscuelas.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblEscuelas.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        jLabel1.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escuelas");

        btnAgregarEscuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar1.png"))); // NOI18N
        btnAgregarEscuela.setBorder(null);
        btnAgregarEscuela.setBorderPainted(false);
        btnAgregarEscuela.setContentAreaFilled(false);
        btnAgregarEscuela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarEscuela.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar2.png"))); // NOI18N
        btnAgregarEscuela.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar3.png"))); // NOI18N
        btnAgregarEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEscuelaActionPerformed(evt);
            }
        });

        btnEditarEscuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar1.png"))); // NOI18N
        btnEditarEscuela.setContentAreaFilled(false);
        btnEditarEscuela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarEscuela.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar2.png"))); // NOI18N
        btnEditarEscuela.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar3.png"))); // NOI18N
        btnEditarEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEscuelaActionPerformed(evt);
            }
        });

        btnEliminarEscuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar1.png"))); // NOI18N
        btnEliminarEscuela.setContentAreaFilled(false);
        btnEliminarEscuela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEscuela.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar2.png"))); // NOI18N
        btnEliminarEscuela.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar3.png"))); // NOI18N
        btnEliminarEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEscuelaActionPerformed(evt);
            }
        });

        txtEscuela.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel8.setText("Escuela:");

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEscuelasLayout = new javax.swing.GroupLayout(jPanelEscuelas);
        jPanelEscuelas.setLayout(jPanelEscuelasLayout);
        jPanelEscuelasLayout.setHorizontalGroup(
            jPanelEscuelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEscuelasLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanelEscuelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEscuelasLayout.createSequentialGroup()
                        .addGroup(jPanelEscuelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEscuelasLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEscuelasLayout.createSequentialGroup()
                        .addComponent(btnAgregarEscuela)
                        .addGap(75, 75, 75)
                        .addComponent(btnEditarEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnEliminarEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        jPanelEscuelasLayout.setVerticalGroup(
            jPanelEscuelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscuelasLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanelEscuelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnBuscar1))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanelEscuelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEscuelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAgregarEscuela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarEscuela, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnEliminarEscuela, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout jPanelEscuelaLayout = new javax.swing.GroupLayout(jPanelEscuela);
        jPanelEscuela.setLayout(jPanelEscuelaLayout);
        jPanelEscuelaLayout.setHorizontalGroup(
            jPanelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEscuelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEscuelaLayout.setVerticalGroup(
            jPanelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscuelaLayout.createSequentialGroup()
                .addComponent(jPanelEscuelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Escuela", jPanelEscuela);

        jPanelCarrera.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanelCarreraPropertyChange(evt);
            }
        });

        jPanelCarreras.setBackground(new java.awt.Color(248, 255, 255));
        jPanelCarreras.setMaximumSize(new java.awt.Dimension(750, 550));
        jPanelCarreras.setMinimumSize(new java.awt.Dimension(750, 550));

        tblEspecialidad.getTableHeader().setFont(new java.awt.Font("Euphemia", 0, 18));
        tblEspecialidad.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        tblEspecialidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEspecialidad.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblEspecialidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblEspecialidad.setRowHeight(23);
        tblEspecialidad.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblEspecialidad);
        if (tblEspecialidad.getColumnModel().getColumnCount() > 0) {
            tblEspecialidad.getColumnModel().getColumn(0).setMinWidth(0);
            tblEspecialidad.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblEspecialidad.getColumnModel().getColumn(0).setMaxWidth(0);
            tblEspecialidad.getColumnModel().getColumn(1).setMinWidth(383);
            tblEspecialidad.getColumnModel().getColumn(1).setPreferredWidth(383);
            tblEspecialidad.getColumnModel().getColumn(1).setMaxWidth(383);
        }

        jLabel2.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Carrera o Especialidad");

        btnAgregarCarrera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar1.png"))); // NOI18N
        btnAgregarCarrera.setBorder(null);
        btnAgregarCarrera.setBorderPainted(false);
        btnAgregarCarrera.setContentAreaFilled(false);
        btnAgregarCarrera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarCarrera.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar2.png"))); // NOI18N
        btnAgregarCarrera.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar3.png"))); // NOI18N
        btnAgregarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarreraActionPerformed(evt);
            }
        });

        btnEditarCarrera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar1.png"))); // NOI18N
        btnEditarCarrera.setContentAreaFilled(false);
        btnEditarCarrera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarCarrera.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar2.png"))); // NOI18N
        btnEditarCarrera.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar3.png"))); // NOI18N
        btnEditarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCarreraActionPerformed(evt);
            }
        });

        btnEliminarCarrera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar1.png"))); // NOI18N
        btnEliminarCarrera.setContentAreaFilled(false);
        btnEliminarCarrera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCarrera.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar2.png"))); // NOI18N
        btnEliminarCarrera.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar3.png"))); // NOI18N
        btnEliminarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCarreraActionPerformed(evt);
            }
        });

        txtEspecialidad.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel4.setText("Especialidad:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCarrerasLayout = new javax.swing.GroupLayout(jPanelCarreras);
        jPanelCarreras.setLayout(jPanelCarrerasLayout);
        jPanelCarrerasLayout.setHorizontalGroup(
            jPanelCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarrerasLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(btnAgregarCarrera)
                .addGap(95, 95, 95)
                .addComponent(btnEditarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(btnEliminarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelCarrerasLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(jPanelCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCarrerasLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEspecialidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanelCarrerasLayout.setVerticalGroup(
            jPanelCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarrerasLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanelCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanelCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAgregarCarrera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarCarrera, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnEliminarCarrera))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout jPanelCarreraLayout = new javax.swing.GroupLayout(jPanelCarrera);
        jPanelCarrera.setLayout(jPanelCarreraLayout);
        jPanelCarreraLayout.setHorizontalGroup(
            jPanelCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCarreraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCarreraLayout.setVerticalGroup(
            jPanelCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCarreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Carrera o especialidad", jPanelCarrera);

        jPanelMetal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanelMetalPropertyChange(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(248, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(750, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 550));

        tblMetales.getTableHeader().setFont(new java.awt.Font("Euphemia", 0, 18));
        tblMetales.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        tblMetales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMetales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblMetales.setRowHeight(23);
        tblMetales.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tblMetales);
        if (tblMetales.getColumnModel().getColumnCount() > 0) {
            tblMetales.getColumnModel().getColumn(0).setMinWidth(0);
            tblMetales.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblMetales.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jLabel3.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Metales");

        btnAgregarMetales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar1.png"))); // NOI18N
        btnAgregarMetales.setBorder(null);
        btnAgregarMetales.setBorderPainted(false);
        btnAgregarMetales.setContentAreaFilled(false);
        btnAgregarMetales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarMetales.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar2.png"))); // NOI18N
        btnAgregarMetales.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar3.png"))); // NOI18N
        btnAgregarMetales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMetalesActionPerformed(evt);
            }
        });

        btnEditarMetales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar1.png"))); // NOI18N
        btnEditarMetales.setContentAreaFilled(false);
        btnEditarMetales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarMetales.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar2.png"))); // NOI18N
        btnEditarMetales.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar3.png"))); // NOI18N
        btnEditarMetales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMetalesActionPerformed(evt);
            }
        });

        btnEliminarMetales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar1.png"))); // NOI18N
        btnEliminarMetales.setContentAreaFilled(false);
        btnEliminarMetales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarMetales.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar2.png"))); // NOI18N
        btnEliminarMetales.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar3.png"))); // NOI18N
        btnEliminarMetales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMetalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(btnAgregarMetales)
                .addGap(95, 95, 95)
                .addComponent(btnEditarMetales, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(btnEliminarMetales, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAgregarMetales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarMetales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnEliminarMetales))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout jPanelMetalLayout = new javax.swing.GroupLayout(jPanelMetal);
        jPanelMetal.setLayout(jPanelMetalLayout);
        jPanelMetalLayout.setHorizontalGroup(
            jPanelMetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
            .addGroup(jPanelMetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMetalLayout.setVerticalGroup(
            jPanelMetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
            .addGroup(jPanelMetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Material de anillos", jPanelMetal);

        jPanelEgresos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanelEgresosPropertyChange(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(248, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 550));

        tblEgresos.getTableHeader().setFont(new java.awt.Font("Euphemia", 0, 18));
        tblEgresos.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        tblEgresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEgresos.setRowHeight(23);
        jScrollPane5.setViewportView(tblEgresos);
        if (tblEgresos.getColumnModel().getColumnCount() > 0) {
            tblEgresos.getColumnModel().getColumn(0).setMinWidth(0);
            tblEgresos.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblEgresos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jLabel5.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Inversión");

        btnEditarEgreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar1.png"))); // NOI18N
        btnEditarEgreso.setContentAreaFilled(false);
        btnEditarEgreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarEgreso.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar2.png"))); // NOI18N
        btnEditarEgreso.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar3.png"))); // NOI18N
        btnEditarEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEgresoActionPerformed(evt);
            }
        });

        btnAgregarEgreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar1.png"))); // NOI18N
        btnAgregarEgreso.setBorder(null);
        btnAgregarEgreso.setBorderPainted(false);
        btnAgregarEgreso.setContentAreaFilled(false);
        btnAgregarEgreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarEgreso.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar2.png"))); // NOI18N
        btnAgregarEgreso.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar3.png"))); // NOI18N
        btnAgregarEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEgresoActionPerformed(evt);
            }
        });

        btnEliminarEgreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar1.png"))); // NOI18N
        btnEliminarEgreso.setContentAreaFilled(false);
        btnEliminarEgreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEgreso.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar2.png"))); // NOI18N
        btnEliminarEgreso.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar3.png"))); // NOI18N
        btnEliminarEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEgresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(btnAgregarEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnEditarEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnEliminarEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarEgreso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAgregarEgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarEgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelEgresosLayout = new javax.swing.GroupLayout(jPanelEgresos);
        jPanelEgresos.setLayout(jPanelEgresosLayout);
        jPanelEgresosLayout.setHorizontalGroup(
            jPanelEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        jPanelEgresosLayout.setVerticalGroup(
            jPanelEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Egresos", jPanelEgresos);

        jPanel3.setBackground(new java.awt.Color(248, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(750, 550));
        jPanel3.setMinimumSize(new java.awt.Dimension(750, 550));
        jPanel3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel3PropertyChange(evt);
            }
        });

        tblAgradecimientos.getTableHeader().setFont(new java.awt.Font("Euphemia", 0, 18));
        tblAgradecimientos.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        tblAgradecimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Clave", "Mensaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAgradecimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblAgradecimientos.setRowHeight(23);
        tblAgradecimientos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(tblAgradecimientos);
        if (tblAgradecimientos.getColumnModel().getColumnCount() > 0) {
            tblAgradecimientos.getColumnModel().getColumn(0).setMinWidth(0);
            tblAgradecimientos.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblAgradecimientos.getColumnModel().getColumn(0).setMaxWidth(0);
            tblAgradecimientos.getColumnModel().getColumn(1).setMinWidth(150);
            tblAgradecimientos.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblAgradecimientos.getColumnModel().getColumn(1).setMaxWidth(150);
            tblAgradecimientos.getColumnModel().getColumn(2).setResizable(false);
            tblAgradecimientos.getColumnModel().getColumn(2).setPreferredWidth(450);
        }

        jLabel6.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Agradecimientos");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar1.png"))); // NOI18N
        btnAgregar.setBorder(null);
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar2.png"))); // NOI18N
        btnAgregar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar3.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar1.png"))); // NOI18N
        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar2.png"))); // NOI18N
        btnEditar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar3.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar1.png"))); // NOI18N
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar2.png"))); // NOI18N
        btnEliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar3.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(95, 95, 95)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnEliminar))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout jPanelAgradecimientosLayout = new javax.swing.GroupLayout(jPanelAgradecimientos);
        jPanelAgradecimientos.setLayout(jPanelAgradecimientosLayout);
        jPanelAgradecimientosLayout.setHorizontalGroup(
            jPanelAgradecimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAgradecimientosLayout.setVerticalGroup(
            jPanelAgradecimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Agradecimientos", jPanelAgradecimientos);

        jPanelModelos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanelModelosPropertyChange(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(248, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(750, 550));
        jPanel5.setMinimumSize(new java.awt.Dimension(750, 550));

        tblModelos.getTableHeader().setFont(new java.awt.Font("Euphemia", 0, 18));
        tblModelos.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        tblModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblModelos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblModelos.setRowHeight(23);
        tblModelos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane7.setViewportView(tblModelos);
        if (tblModelos.getColumnModel().getColumnCount() > 0) {
            tblModelos.getColumnModel().getColumn(0).setMinWidth(0);
            tblModelos.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblModelos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jLabel7.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Modelos");

        btnAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar1.png"))); // NOI18N
        btnAgregar1.setBorder(null);
        btnAgregar1.setBorderPainted(false);
        btnAgregar1.setContentAreaFilled(false);
        btnAgregar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar2.png"))); // NOI18N
        btnAgregar1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar3.png"))); // NOI18N
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar1.png"))); // NOI18N
        btnEditar1.setContentAreaFilled(false);
        btnEditar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar2.png"))); // NOI18N
        btnEditar1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar3.png"))); // NOI18N
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar1.png"))); // NOI18N
        btnEliminar1.setContentAreaFilled(false);
        btnEliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar2.png"))); // NOI18N
        btnEliminar1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar3.png"))); // NOI18N
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(btnAgregar1)
                .addGap(95, 95, 95)
                .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAgregar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnEliminar1))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout jPanelModelosLayout = new javax.swing.GroupLayout(jPanelModelos);
        jPanelModelos.setLayout(jPanelModelosLayout);
        jPanelModelosLayout.setHorizontalGroup(
            jPanelModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
            .addGroup(jPanelModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelModelosLayout.setVerticalGroup(
            jPanelModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
            .addGroup(jPanelModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modelos de marco", jPanelModelos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCarreraActionPerformed
        // TODO add your handling code here:
        try
        {
            btnEliminarEscuela.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if(tblEspecialidad.getSelectedRow()!= -1){

                int opcion = JOptionPane.showConfirmDialog(null, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("Eliminar"), ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloEspecialidad"), JOptionPane.YES_NO_OPTION);
                if(opcion==0){
                    int id = Integer.parseInt(tblEspecialidad.getValueAt(tblEspecialidad.getSelectedRow(), 0).toString());
                    if(EspecialidadNegocio.Eliminar(id)){
                        cargarEspecialidades();
                    }
                }

            }else{
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("SeleccionElemento")
                    , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloEspecialidad"), JOptionPane.INFORMATION_MESSAGE);
            }

        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
  }finally{
            btnEliminarEscuela.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnEliminarCarreraActionPerformed

    private void btnEditarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCarreraActionPerformed
        // TODO add your handling code here:
        try
        {   btnEditarEscuela.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if(tblEspecialidad.getSelectedRow()!= -1){
                int id = Integer.parseInt(tblEspecialidad.getValueAt(tblEspecialidad.getSelectedRow(), 0).toString());

                JDialogAgregarEspecialidad agregar = new JDialogAgregarEspecialidad(null, true);

                //this.setVisible(true);
                agregar.id = id;
                agregar.editar=true;
                agregar.setVisible(true);
                if (agregar.DialogResult)
                {
                    cargarEspecialidades();
                }
            }else{
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("SeleccionElemento")
                    , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloEspecialidad"), JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
  }finally{
            btnEditarEscuela.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnEditarCarreraActionPerformed

    private void btnAgregarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarreraActionPerformed
        // TODO add your handling code here:
        try
        {
            btnAgregarEscuela.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            JDialogAgregarEspecialidad especialidad = new JDialogAgregarEspecialidad(null, true);
            especialidad.setVisible(true);
            if(especialidad.DialogResult)
            {
                cargarEspecialidades();
            }
        }
       catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
    }finally{
            btnAgregarEscuela.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        }
    }//GEN-LAST:event_btnAgregarCarreraActionPerformed

    private void btnEliminarEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEscuelaActionPerformed
        // TODO add your handling code here:
        try
        {
            btnEliminarEscuela.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if(tblEscuelas.getSelectedRow()!= -1){

                int opcion = JOptionPane.showConfirmDialog(null, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("Eliminar"), ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloUsuario"), JOptionPane.YES_NO_OPTION);
                if(opcion==0){
                    int id = Integer.parseInt(tblEscuelas.getValueAt(tblEscuelas.getSelectedRow(), 0).toString());
                    if(EscuelaNegocio.Eliminar(id)){
                        cargarEscuelas();
                    }
                }

            }else{
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("SeleccionElemento")
                    , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloUsuario"), JOptionPane.INFORMATION_MESSAGE);
            }

        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
    }finally{
            btnEliminarEscuela.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnEliminarEscuelaActionPerformed

    private void btnEditarEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEscuelaActionPerformed
        // TODO add your handling code here:
        try
        {   btnEditarEscuela.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if(tblEscuelas.getSelectedRow()!= -1){
                int id = Integer.parseInt(tblEscuelas.getValueAt(tblEscuelas.getSelectedRow(), 0).toString());

                JDialogAgregarEscuela agregar = new JDialogAgregarEscuela(null, true);

                //this.setVisible(true);
                agregar.id = id;
                agregar.editar=true;
                agregar.setVisible(true);
                if (agregar.DialogResult)
                {
                    cargarEscuelas();
                }
            }else{
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("SeleccionElemento")
                    , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloEscuela"), JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
   }finally{
            btnEditarEscuela.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnEditarEscuelaActionPerformed

    private void btnAgregarEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEscuelaActionPerformed
        // TODO add your handling code here:
        try
        {
            btnAgregarEscuela.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            JDialogAgregarEscuela escuela = new JDialogAgregarEscuela(null, true);
            escuela.setVisible(true);
            if(escuela.DialogResult)
            {
                cargarEscuelas();
            }
        }
       catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
      }finally{
            btnAgregarEscuela.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        }
    }//GEN-LAST:event_btnAgregarEscuelaActionPerformed

    private void jPanelCarreraPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanelCarreraPropertyChange
        // TODO add your handling code here:
        cargarEspecialidades();
    }//GEN-LAST:event_jPanelCarreraPropertyChange

    private void btnAgregarMetalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMetalesActionPerformed
        // TODO add your handling code here:
        try
        {
            btnAgregarMetales.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            JDialogAgregarMetal escuela = new JDialogAgregarMetal(null, true);
            escuela.setVisible(true);
            if(escuela.DialogResult)
            {
                cargarMetales();
            }
        }
       catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
   }finally{
            btnAgregarMetales.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        }
    }//GEN-LAST:event_btnAgregarMetalesActionPerformed

    private void btnEditarMetalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMetalesActionPerformed
        // TODO add your handling code here:
        try
        {
            btnEditarMetales.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if(tblMetales.getSelectedRow()!= -1&&tblMetales.getSelectedRow()!=0){
                int id = Integer.parseInt(tblMetales.getValueAt(tblMetales.getSelectedRow(), 0).toString());

                JDialogAgregarMetal agregar = new JDialogAgregarMetal(null, true);
                agregar.id = id;
                agregar.editar=true;
                agregar.setVisible(true);
                if (agregar.DialogResult)
                {
                    cargarMetales();
                }
            }else{
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("SeleccionElemento")
                    , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloMetal"), JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
  }finally{
            btnEditarMetales.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnEditarMetalesActionPerformed

    private void btnEliminarMetalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMetalesActionPerformed
        // TODO add your handling code here:
        try
        {
            btnEliminarMetales.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if(tblMetales.getSelectedRow()!= -1 && tblMetales.getSelectedRow()!=0)
            {

                int opcion = JOptionPane.showConfirmDialog(null, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("Eliminar"), ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloMetal"), JOptionPane.YES_NO_OPTION);
                if(opcion==0){
                    int id = Integer.parseInt(tblMetales.getValueAt(tblMetales.getSelectedRow(), 0).toString());
                    if(MetalNegocio.Eliminar(id)){
                        cargarMetales();
                    }
                }

            }
            else
            {
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("SeleccionElemento")
                    , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloMetal"), JOptionPane.INFORMATION_MESSAGE);
            }

        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
  }finally{
            btnEliminarMetales.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnEliminarMetalesActionPerformed

    private void jPanelMetalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanelMetalPropertyChange
        // TODO add your handling code here:
        cargarMetales();
    }//GEN-LAST:event_jPanelMetalPropertyChange

    private void btnEditarEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEgresoActionPerformed
        // TODO add your handling code here:
        try
        {   btnEditarEgreso.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if(tblEgresos.getSelectedRow()!= -1){
                int id = Integer.parseInt(tblEgresos.getValueAt(tblEgresos.getSelectedRow(), 0).toString());

                JDialogAgregarEgreso agregar = new JDialogAgregarEgreso(null, true);

                //this.setVisible(true);
                agregar.id = id;
                agregar.editar=true;
                agregar.setVisible(true);
                if (agregar.DialogResult)
                {
                    cargarEgresos();
                }
            }else{
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("SeleccionElemento")
                    , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloEspecialidad"), JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
     }finally{
            btnEditarEgreso.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnEditarEgresoActionPerformed

    private void btnAgregarEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEgresoActionPerformed
        // TODO add your handling code here:+
        try
        {
            btnAgregarEgreso.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            JDialogAgregarEgreso egreso = new JDialogAgregarEgreso(null, true);
            egreso.setVisible(true);
            if(egreso.DialogResult)
            {
                cargarEgresos();
            }
        }
       catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
    }finally{
            btnAgregarEgreso.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        }
    }//GEN-LAST:event_btnAgregarEgresoActionPerformed

    private void btnEliminarEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEgresoActionPerformed
        // TODO add your handling code here:
        try
        {
            btnEliminarEgreso.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if(tblEgresos.getSelectedRow()!= -1){

                int opcion = JOptionPane.showConfirmDialog(null, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("Eliminar"), ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloEspecialidad"), JOptionPane.YES_NO_OPTION);
                if(opcion==0){
                    int id = Integer.parseInt(tblEgresos.getValueAt(tblEgresos.getSelectedRow(), 0).toString());
                    if(EgresoNegocio.Eliminar(id)){
                        cargarEgresos();
                    }
                }

            }else{
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("SeleccionElemento")
                    , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloEspecialidad"), JOptionPane.INFORMATION_MESSAGE);
            }

        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
    }finally{
            btnEliminarEgreso.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnEliminarEgresoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try
        {
            btnAgregar.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            JDialogAgregarAgradecimiento dialog = new JDialogAgregarAgradecimiento(null, true);
            dialog.setVisible(true);
            if(dialog.DialogResult)
            {
                cargarAgradecimientos();
            }
        }
    catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
      }finally{
            btnAgregar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        try
        {
            btnEditar.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if(tblAgradecimientos.getSelectedRow()!= -1){
                int id = Integer.parseInt(tblAgradecimientos.getValueAt(tblAgradecimientos.getSelectedRow(), 0).toString());
                if (!AgradecimientoNegocio.ValidarEdicion(id))
                {
                    JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("AgradecimientoNoEliminar")
                        , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloAgradecimiento"), JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                JDialogAgregarAgradecimiento agregar = new JDialogAgregarAgradecimiento(null, true);
                agregar.id = id;
                agregar.editar=true;
                agregar.setVisible(true);
                if (agregar.DialogResult)
                {
                    cargarAgradecimientos();
                }
            }else{
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("SeleccionElemento")
                    , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloAgradecimiento"), JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
     }finally{
            btnEditar.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try
        {
            btnEliminar.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if(tblAgradecimientos.getSelectedRow()!= -1)
            {
                int id = Integer.parseInt(tblAgradecimientos.getValueAt(tblAgradecimientos.getSelectedRow(), 0).toString());
                if (!AgradecimientoNegocio.ValidarEdicion(id))
                {
                    JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("AgradecimientoNoEliminar")
                        , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloAgradecimiento"), JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                int opcion = JOptionPane.showConfirmDialog(null, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("Eliminar"),
                    ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloAgradecimiento"), JOptionPane.YES_NO_OPTION);
                if(opcion==0){
                    if(AgradecimientoNegocio.Eliminar(id)){
                        cargarAgradecimientos();
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("SeleccionElemento")
                    , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloAgradecimiento"), JOptionPane.INFORMATION_MESSAGE);
            }

        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
  }finally{
            btnEliminar.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jPanel3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel3PropertyChange
        // TODO add your handling code here:
        cargarAgradecimientos();
    }//GEN-LAST:event_jPanel3PropertyChange

    private void jPanelEgresosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanelEgresosPropertyChange
        // TODO add your handling code here:
        cargarEgresos();
    }//GEN-LAST:event_jPanelEgresosPropertyChange

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        // TODO add your handling code here:
        try
        {
            btnAgregar.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            JDialogAgregarModelo escuela = new JDialogAgregarModelo(null, true);
            escuela.setVisible(true);
            if(escuela.DialogResult)
            {
                cargarModelos();
            }
        }
     catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
      }finally{
            btnAgregar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        }
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
        try
        {
            btnEditar.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if(tblModelos.getSelectedRow()!= -1){
                int id = Integer.parseInt(tblModelos.getValueAt(tblModelos.getSelectedRow(), 0).toString());

                JDialogAgregarModelo agregar = new JDialogAgregarModelo(null, true);
                agregar.id = id;
                agregar.editar=true;
                agregar.setVisible(true);
                if (agregar.DialogResult)
                {
                    cargarModelos();
                }
            }else{
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("SeleccionElemento")
                    , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloModelo"), JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
   }finally{
            btnEditar.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        try
        {
            btnEliminar.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if(tblModelos.getSelectedRow()!= -1)
            {

                int opcion = JOptionPane.showConfirmDialog(null, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("Eliminar"), ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloModelo"), JOptionPane.YES_NO_OPTION);
                if(opcion==0){
                    int id = Integer.parseInt(tblModelos.getValueAt(tblModelos.getSelectedRow(), 0).toString());
                    if(ModeloNegocio.Eliminar(id)){
                        cargarModelos();
                    }
                }

            }
            else
            {
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("SeleccionElemento")
                    , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloModelo"), JOptionPane.INFORMATION_MESSAGE);
            }

        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
  }finally{
            btnEliminar.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void jPanelModelosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanelModelosPropertyChange
        // TODO add your handling code here:
        cargarModelos();
    }//GEN-LAST:event_jPanelModelosPropertyChange

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try
        {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            buscarEspecialidad();
        }catch(Exception ex)
        {
            Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
        }
        finally
        {
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
         try
        {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            buscarEscuela();
        }catch(Exception ex)
        {
            Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
        }
        finally
        {
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnAgregarCarrera;
    private javax.swing.JButton btnAgregarEgreso;
    private javax.swing.JButton btnAgregarEscuela;
    private javax.swing.JButton btnAgregarMetales;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEditarCarrera;
    private javax.swing.JButton btnEditarEgreso;
    private javax.swing.JButton btnEditarEscuela;
    private javax.swing.JButton btnEditarMetales;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnEliminarCarrera;
    private javax.swing.JButton btnEliminarEgreso;
    private javax.swing.JButton btnEliminarEscuela;
    private javax.swing.JButton btnEliminarMetales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelAgradecimientos;
    private javax.swing.JPanel jPanelCarrera;
    private javax.swing.JPanel jPanelCarreras;
    private javax.swing.JPanel jPanelEgresos;
    private javax.swing.JPanel jPanelEscuela;
    private javax.swing.JPanel jPanelEscuelas;
    private javax.swing.JPanel jPanelMetal;
    private javax.swing.JPanel jPanelModelos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblAgradecimientos;
    private javax.swing.JTable tblEgresos;
    private javax.swing.JTable tblEscuelas;
    private javax.swing.JTable tblEspecialidad;
    private javax.swing.JTable tblMetales;
    private javax.swing.JTable tblModelos;
    private javax.swing.JTextField txtEscuela;
    private javax.swing.JTextField txtEspecialidad;
    // End of variables declaration//GEN-END:variables

    private void cargarEscuelas() {
          try
        { 
            escuelas = EscuelaNegocio.Listado();
            cargarTablaEscuela();
        }
        catch(Exception ex)
        {
            Program.logger.error(this, ex);
        }
        finally
        {
            this.setCursor(Cursor.getDefaultCursor());
        }    
        }     

    private void cargarEspecialidades() {
         try
        { 
            especialidades = EspecialidadNegocio.Listado();
            cargarTablaEspecialidad();
        }
        catch(Exception ex)
        {
            Program.logger.error(this, ex);
        }
        finally
        {
            this.setCursor(Cursor.getDefaultCursor());
        }    
    } 

    private void cargarModelos() {
        try{
     DefaultTableModel mod = (DefaultTableModel)tblModelos.getModel();
        while(mod.getRowCount() > 0)
            mod.removeRow(0);
        
        modelos = ModeloNegocio.Listado();
        for(Modelo entidad : modelos){
            int id = entidad.getId();
            String nombre = entidad.getNombre(); 
            mod.addRow(new Object[] {id, nombre});
        } 
        tblModelos.setModel(mod);
    }  catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
    }    }

    private void cargarMetales() {
        try{
            
        
          DefaultTableModel mod = (DefaultTableModel)tblMetales.getModel();
        while(mod.getRowCount() > 0)
            mod.removeRow(0);
        
        metales = MetalNegocio.Listado();
        for(Metal entidad : metales){
            int id = entidad.getId();
            String nombre = entidad.getNombre(); 
            mod.addRow(new Object[] {id, nombre});
        } 
        tblMetales.setModel(mod);
    }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
        }   }

    private void cargarEgresos() {
        try{
      DefaultTableModel mod = (DefaultTableModel)tblEgresos.getModel();
        while(mod.getRowCount() > 0)
            mod.removeRow(0);
        
        egresos = EgresoNegocio.Listado();
        for(Egreso egreso : egresos){
            int id = egreso.getId();
            String nombre = egreso.getNombre();
           
                 
            mod.addRow(new Object[] {id, nombre});
        }
        
        tblEgresos.setModel(mod);
    } catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
    }  }

    private void cargarAgradecimientos() {
        try{
            
        
         DefaultTableModel mod = (DefaultTableModel)tblAgradecimientos.getModel();
        while(mod.getRowCount() > 0)
            mod.removeRow(0);
        
        agradecimientos = AgradecimientoNegocio.Listado();
        for(Agradecimiento entidad : agradecimientos){
            int id = entidad.getId();
            String nombre = entidad.getClave(); 
            String mensaje = entidad.getMensaje();
            mod.addRow(new Object[] {id, nombre, mensaje});
        } 
        tblAgradecimientos.setModel(mod);
    
    }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
}
    }

    private void buscarEspecialidad() {
         try
        { 
            String nombre =txtEspecialidad.getText().trim();
            especialidades = EspecialidadNegocio.Buscar(nombre);
            cargarTablaEspecialidad();
        }
        catch(Exception ex)
        {
            Program.logger.error(this, ex);
        }
        finally
        {
            this.setCursor(Cursor.getDefaultCursor());
        }
    }

    private void cargarTablaEspecialidad() {
            try{
      DefaultTableModel mod = (DefaultTableModel)tblEspecialidad.getModel();
       mod.setRowCount(0);
        
      
        for(Especialidad especialidad : especialidades){
            int id = especialidad.getId();
            String nombre = especialidad.getNombre();
           
                 
            mod.addRow(new Object[] {id, nombre});
        }
        
        tblEspecialidad.setModel(mod);
      
    }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
}
       }

    private void cargarTablaEscuela() {
        try{
        DefaultTableModel mod = (DefaultTableModel)tblEscuelas.getModel();
         mod.setRowCount(0);
        for(Escuela escuela : escuelas){
            int id = escuela.getId();
            String nombre = escuela.getNombre();
            String ciudad = escuela.getCiudad();                                     
            mod.addRow(new Object[] {id, nombre, ciudad});
        }        
        tblEscuelas.setModel(mod);
        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
        }
    
    }

    private void buscarEscuela() {
         try
        { 
            String nombre =txtEscuela.getText().trim();
            escuelas = EscuelaNegocio.Buscar(nombre);
            cargarTablaEscuela();
        }
        catch(Exception ex)
        {
            Program.logger.error(this, ex);
        }
        finally
        {
            this.setCursor(Cursor.getDefaultCursor());
        }
         }
}
 
    
          
    

