/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gdm;

import gdm.entidades.clases.Contrato;
import gdm.entidades.clases.Egreso;
import gdm.entidades.clases.EgresoValor;
import java.awt.Cursor;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import negocio.Clases.ContratoNegocio;
import negocio.Clases.EgresoNegocio;
import negocio.Clases.EgresoValorNegocio;

/**
 *
 * @author Chuy
 */
public class JDialogAgregarInversion extends javax.swing.JDialog {

    /**
     * Creates new form JDialogAgregarInversion
     */
    public JDialogAgregarInversion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public boolean DialogResult = false;
    Egreso egreso = new Egreso();
    public Integer id = 0;
    public int idCon = 0;
     public boolean editar = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboEgreso = new gdm.presentacion.CustomComboBox();
        txtValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inversión");

        txtValor.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel2.setText("Valor");

        btnAceptar4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Aceptar1.png"))); // NOI18N
        btnAceptar4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAceptar4.setBorderPainted(false);
        btnAceptar4.setContentAreaFilled(false);
        btnAceptar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptar4.setIconTextGap(-3);
        btnAceptar4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Aceptar2.png"))); // NOI18N
        btnAceptar4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Aceptar3.png"))); // NOI18N
        btnAceptar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboEgreso, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(txtValor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 130, Short.MAX_VALUE)
                .addComponent(btnAceptar4)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(comboEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAceptar4)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar4ActionPerformed
        // TODO add your handling code here:
    try{
          
      
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
          egreso.setId(Integer.parseInt(comboEgreso.getSelectedValue().toString()));
          egreso.setNombre(comboEgreso.getSelectedValue().toString());               
          
          if(comboEgreso.getSelectedIndex()!= -1&&!txtValor.getText().trim().isEmpty())
          { 
              if(EgresoValorNegocio.Guardar(idCon, Integer.parseInt(comboEgreso.getSelectedValue().toString()), Double.parseDouble(txtValor.getText()))){
                if (!sumarEgreso())
                {
                    JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("AbonoMayorTotal")
                        , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloAnticipo"), JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                  this.DialogResult=true;            
                this.dispose();
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("EgresoAgregado")
                            , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloEgreso"), JOptionPane.INFORMATION_MESSAGE); 
              }else{
              JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);

              }
                 
          }else{
           JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("CamposVacios")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloEgreso"), JOptionPane.INFORMATION_MESSAGE);

          }
    }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
} 
        

    }//GEN-LAST:event_btnAceptar4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here: 
        try{
         //Asigna el nombre del atributo  que tendra el valor del combo seleccionado.
          
           comboEgreso.setValueMember("id");
            //Asigna el nombre del atributo a el valor que mostrara el combo.
           comboEgreso.setDisplayMember("nombre");
           //Asigna la lista de valores a el combo
           comboEgreso.setDataSource(EgresoNegocio.Listado());
           comboEgreso.setSelectedIndex(-1);
           
           if(editar){
                cargarEdicion();
           }
        }catch(Exception ex){
              Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
 
     
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        // TODO add your handling code here:
        
           // TODO add your handling code here:
        char car = evt.getKeyChar();        
        if(((car < '0') || (car > '9'))&& (car !='.'))evt.consume();{  
        if (car == '.' && txtValor.getText().contains(".")) { evt.consume(); }
        
    }
    }//GEN-LAST:event_txtValorKeyTyped

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar4;
    private gdm.presentacion.CustomComboBox comboEgreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    private void cargarEdicion() {
              try{
                   
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        EgresoValor egreso =EgresoValorNegocio.Obtener(id);
        if(egreso != null){
            
            txtValor.setText(egreso.getValor().toString());    
            comboEgreso.setSelectedValue(egreso.getEgreso().getId());
            
        }
     }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
  }
        finally{
          this.setCursor(Cursor.getDefaultCursor());     
        }  
    }

    private boolean sumarEgreso() {
      boolean guardar=false;
       Contrato contrato = ContratoNegocio.Obtener(idCon);
        try
        {   
            if(contrato.getGanancia()==0&&contrato.getEgresoValor()==null){
                 double cantidad = ContratoNegocio.TotalGanancia(idCon);
                 double valor = Double.parseDouble(txtValor.getText().trim());
                 double ganancia = cantidad-valor;
                 contrato.setGanancia(ganancia);          
            }
            else{
                double cantidad =contrato.getGanancia();
                double valor = Double.parseDouble(txtValor.getText().trim());
                double ganancia = cantidad-valor;
                contrato.setGanancia(ganancia);
            }
           guardar= true;
               
        }catch(Exception ex)
        {
             Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);      
        }
        return guardar;
    }
    
    }

