/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gdm;

import gdm.entidades.clases.Agradecimiento;
import gdm.entidades.clases.Anillo;
import gdm.entidades.clases.Anticipo;
import gdm.entidades.clases.Cliente;
import gdm.entidades.clases.Common;
import gdm.entidades.clases.Contrato;
import gdm.entidades.clases.ContratoCliente;
import gdm.entidades.clases.FotoPanoramica;
import gdm.entidades.clases.Metal;
import gdm.entidades.clases.Modelo;
import gdm.filechooser.ImageFileView;
import gdm.filechooser.ImageFilter;
import gdm.filechooser.ImagePreview;
import java.awt.Cursor;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import negocio.Clases.AgradecimientoNegocio;
import negocio.Clases.ClienteNegocio;
import negocio.Clases.ContratoClienteNegocio;
import negocio.Clases.ContratoNegocio;
import negocio.Clases.MetalNegocio;
import negocio.Clases.ModeloNegocio;

/**
 *
 * @author Chuy
 */
public class JDialogAgregarContratoCliente extends javax.swing.JDialog {
public boolean editar = false;
 public Integer id = 0;
    /**
     * Creates new form JDialogAgregarContratoCliente
     */
    public JDialogAgregarContratoCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    Modelo modelo = new Modelo();
    Agradecimiento agradecimiento = new Agradecimiento();
    List<Agradecimiento> agradecimientos = new ArrayList<Agradecimiento>();
//    List<Anticipo> anticipos = new ArrayList();
    String mensaje = null;
    Anillo anillo = new Anillo();
    Metal metal = new Metal();
    public int idContrato = 0;
    public int idCliente= 0;
    public int idAnillo=0;
    String dirigido;
    Cliente cliente = new Cliente();
    public boolean DialogResult = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField12 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        btnCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        txtEscuela = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtEspecialidad = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtGeneracion = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        comboModelo = new gdm.presentacion.CustomComboBox();
        jLabel9 = new javax.swing.JLabel();
        imgModelo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rbReconocimiento = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        comboDirigido = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtDirigido = new javax.swing.JTextField();
        rbTriptico = new javax.swing.JRadioButton();
        comboAgradecimiento = new gdm.presentacion.CustomComboBox();
        rbTitulo = new javax.swing.JRadioButton();
        btnAdjuntar = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        txtAgra = new javax.swing.JLabel();
        btnRemover = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rbFotoPanoramica = new javax.swing.JRadioButton();
        rbFotoPersonalizada = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        rbFotoMisa = new javax.swing.JRadioButton();
        rbFotoEstudio = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtKilates = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtGramos = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        comboMaterial = new gdm.presentacion.CustomComboBox();
        jPanel11 = new javax.swing.JPanel();
        rbRentaToga = new javax.swing.JRadioButton();
        rbMisa = new javax.swing.JRadioButton();
        rbBaile = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        spMesaExtra = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        spFotosExtra = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        dateFechaContrato = new org.jdesktop.swingx.JXDatePicker();
        jLabel17 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        dateEntregaDatos = new org.jdesktop.swingx.JXDatePicker();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        dateLimitePago = new org.jdesktop.swingx.JXDatePicker();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        dateEntregaPaquete = new org.jdesktop.swingx.JXDatePicker();
        jPanel14 = new javax.swing.JPanel();
        imgFoto = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        btnAgregarImagen = new javax.swing.JButton();
        btnRetirarImagen = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        jTextField12.setText("jTextField12");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(164, 76));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(700, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel6.setText("Cliente");

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCliente.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        btnCliente.setText("Nuevo Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel1.setText("Nombre :");

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N

        txtTelefono.setEditable(false);
        txtTelefono.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel2.setText("Teléfono:");

        txtCelular.setEditable(false);
        txtCelular.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel3.setText("Celular:");

        jLabel4.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel4.setText("Correo:");

        txtCorreo.setEditable(false);
        txtCorreo.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N

        txtDireccion.setEditable(false);
        txtDireccion.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel5.setText("Direccion:");

        btnBuscarCliente.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        btnBuscarCliente.setText("Buscar Cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCliente))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCliente)
                    .addComponent(btnBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel32.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel32.setText("Escuela:");

        txtEscuela.setEditable(false);
        txtEscuela.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel33.setText("Especialidad:");

        txtEspecialidad.setEditable(false);
        txtEspecialidad.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel34.setText("Generación:");

        txtGeneracion.setEditable(false);
        txtGeneracion.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel6)
                .addContainerGap(453, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel32)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEscuela)
                            .addComponent(txtEspecialidad)
                            .addComponent(txtGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88))
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(155, 155, 155))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Infotmación delCliente", jPanel2);

        comboModelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboModeloItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel9.setText("Modelo:");

        imgModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(imgModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addGap(315, 315, 315))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(imgModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modelo de marco", jPanel13);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rbReconocimiento.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        rbReconocimiento.setText("Reconocimiento");

        jLabel7.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel7.setText("Agradecimiento #:");

        comboDirigido.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        comboDirigido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mis Padres", "Mi Familia", "Otro" }));
        comboDirigido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDirigidoItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel8.setText("Dirigido a:");

        txtDirigido.setEditable(false);
        txtDirigido.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        txtDirigido.setEnabled(false);

        rbTriptico.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        rbTriptico.setText("Triptico");

        comboAgradecimiento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboAgradecimientoItemStateChanged(evt);
            }
        });

        rbTitulo.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        rbTitulo.setText("Título");

        btnAdjuntar.setText("Adjuntar archivo");
        btnAdjuntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdjuntarActionPerformed(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtAgra.setBackground(new java.awt.Color(250, 250, 250));
        txtAgra.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        txtAgra.setForeground(new java.awt.Color(0, 135, 191));
        txtAgra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnRemover.setText("X");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAgra, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemover))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAgra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboAgradecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbTriptico, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbTitulo)
                                .addGap(18, 18, 18)
                                .addComponent(rbReconocimiento))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDirigido)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboDirigido, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnAdjuntar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTriptico)
                    .addComponent(rbReconocimiento)
                    .addComponent(rbTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboAgradecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdjuntar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboDirigido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtDirigido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jLabel10.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel10.setText("Paquete");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rbFotoPanoramica.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        rbFotoPanoramica.setText("Foto panoramica");

        rbFotoPersonalizada.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        rbFotoPersonalizada.setText("Foto Personalizada");

        jLabel12.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel12.setText("Foto Evento");

        rbFotoMisa.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        rbFotoMisa.setText("Misa");

        rbFotoEstudio.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        rbFotoEstudio.setText("Estudio");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rbFotoMisa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbFotoEstudio))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rbFotoPanoramica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbFotoPersonalizada)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFotoPersonalizada)
                    .addComponent(rbFotoPanoramica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFotoMisa)
                    .addComponent(rbFotoEstudio))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel13.setText("Anillos");

        txtKilates.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        txtKilates.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtKilates.setText("0");
        txtKilates.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKilatesKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel14.setText("Kilates:");

        jLabel15.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel15.setText("Gramos:");

        txtGramos.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        txtGramos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGramos.setText("0");
        txtGramos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGramosKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel20.setText("Material:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKilates, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGramos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(comboMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKilates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(txtGramos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rbRentaToga.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        rbRentaToga.setText("Renta de toga");

        rbMisa.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        rbMisa.setText("Misa");

        rbBaile.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        rbBaile.setText("Baile");

        jLabel28.setText("Evento");

        jLabel29.setText("Mesa extra:");

        spMesaExtra.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));

        jLabel30.setText("Fotos extra:");

        spFotosExtra.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(rbRentaToga)
                        .addGap(46, 46, 46)
                        .addComponent(rbMisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbBaile)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spFotosExtra)
                                    .addComponent(spMesaExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRentaToga)
                    .addComponent(rbMisa)
                    .addComponent(rbBaile))
                .addGap(11, 11, 11)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(spMesaExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(spFotosExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel31.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel31.setText("Comentarios:");

        txtComentarios.setColumns(20);
        txtComentarios.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        txtComentarios.setRows(5);
        jScrollPane2.setViewportView(txtComentarios);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setText("Precio del paquete: $");

        txtPrecio.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel17.setText("Fecha:");

        txtFolio.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        txtFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFolioKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jLabel11.setText("Folio:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 23, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel31)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(268, 268, 268)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contenido de el Paquete", jPanel1);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel16.setText("Fecha Límite de Entrega de Datos:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(dateEntregaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(dateEntregaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel18.setText("Fecha Límite de Pago:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(dateLimitePago, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(dateLimitePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel19.setText("Fecha de Entrega del Paquete:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(dateEntregaPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(dateEntregaPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(133, 133, 133))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fechas de Entrega ", jPanel6);

        imgFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("Foto del contrato");

        btnAgregarImagen.setText("Seleccionar imagen");
        btnAgregarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarImagenActionPerformed(evt);
            }
        });

        btnRetirarImagen.setText("Remover imagen");
        btnRetirarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel36))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(btnAgregarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRetirarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarImagen)
                    .addComponent(btnRetirarImagen))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Imagen del Contrato", jPanel14);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Aceptar1.png"))); // NOI18N
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Aceptar2.png"))); // NOI18N
        btnAceptar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Aceptar3.png"))); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 647, Short.MAX_VALUE)
                .addComponent(btnAceptar))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange
        // TODO add your handling code here:
         try{
            //Asigna el nombre del atributo  que tendra el valor del combo seleccionado.
           comboModelo.setValueMember("id");
            //Asigna el nombre del atributo a el valor que mostrara el combo.
           comboModelo.setDisplayMember("nombre");
           //Asigna la lista de valores a el combo
           comboModelo.setDataSource(ModeloNegocio.Listado());
           comboModelo.setSelectedIndex(-1);
           
              //Asigna el nombre del atributo  que tendra el valor del combo seleccionado.
           comboAgradecimiento.setValueMember("id");
            //Asigna el nombre del atributo a el valor que mostrara el combo.
           comboAgradecimiento.setDisplayMember("clave");
           //Asigna la lista de valores a el combo
           agradecimientos=AgradecimientoNegocio.Listado();
           comboAgradecimiento.setDataSource(agradecimientos);
           comboAgradecimiento.setSelectedIndex(-1);
           
           List<Metal> lista = new ArrayList();
//           Metal metal = new Metal();
//           metal.setId(0);
//           metal.setNombre("Ninguno");
           lista = MetalNegocio.Listado();
//           lista.add(0,metal);
           //Asigna el nombre del atributo  que tendra el valor del combo seleccionado.                      
           comboMaterial.setValueMember("id");
           //Asigna el nombre del atributo a el valor que mostrara el combo.
           comboMaterial.setDisplayMember("nombre");
           //Asigna la lista de valores a el combo
           comboMaterial.setDataSource(lista);
           comboMaterial.setSelectedIndex(-1);
        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
    
        }
        
    }//GEN-LAST:event_jPanel1PropertyChange

    private void comboModeloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboModeloItemStateChanged
        // TODO add your handling code here:
        try
        {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            int idModelo = Integer.parseInt(comboModelo.getSelectedValue().toString());
            Modelo entidad = ModeloNegocio.Obtener(idModelo);
            if(entidad != null)
            { 
                //txtNombre.setText(entidad.getNombre()); 
                if (!entidad.getImagen().isEmpty())
                {
                    String rutaImagen = ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("rutaImagenes");
                    if (Common.RutaExistente(rutaImagen+entidad.getImagen()))
                    {
                        ImageIcon icon = new ImageIcon(((new ImageIcon(rutaImagen+entidad.getImagen())).getImage())
                            .getScaledInstance(297, 233, java.awt.Image.SCALE_SMOOTH));
                        imgModelo.setIcon(icon);
                    //    rutaArchivo = rutaImagen+entidad.getImagen();
                    }
                }
            }
        }
       catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
 
            
        }
        finally 
        {
            this.setCursor(Cursor.getDefaultCursor());   
        }
    }//GEN-LAST:event_comboModeloItemStateChanged

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        try
        {
            
            if(!editar){        
                
 //           Anticipo ant = new Anticipo();
                
//            String nombre = txtNombreA.getText().trim();
//            String celular = txtCelularA.getText().trim();
//            String telefono = txtTelefonoA.getText().trim();
//            double cantidad = Double.parseDouble(txtCantidadA.getText().trim());
//            String concepto = txtConceptoA.getText().trim();
//            Date fecha = dtFechaA.getDate();
                
//            ant.setNombre(nombre);
//            ant.setCelular(celular);
//            ant.setConcepto(concepto);
//            ant.setTelefono(telefono);
//            ant.setCantidad(cantidad);
//            ant.setRecibo(nombreArchivoA);
//            ant.setFecha(fecha);
//          anticipos.add(ant);
            
            modelo.setId(Integer.parseInt(comboModelo.getSelectedValue().toString()));
            modelo.setImagen(comboModelo.getSelectedValue().toString());
            modelo.setNombre(comboModelo.getSelectedValue().toString());      
            
            
            anillo.setG(Double.parseDouble(txtGramos.getText()));
            anillo.setK(Double.parseDouble(txtKilates.getText()));
            metal.setId(Integer.parseInt(comboMaterial.getSelectedValue().toString()));
            metal.setNombre(comboMaterial.getSelectedValue().toString());
            anillo.setMetal(metal);
            
            int combo = comboDirigido.getSelectedIndex();
            switch(combo){
                case 0: dirigido = "A mis padres"; break;
                case 1: dirigido = "A mi familia"; break;
                case 2: dirigido = txtDirigido.getText(); break;
                    
            } 
                        
            int idAgradecimiento = Integer.parseInt(comboAgradecimiento.getSelectedValue().toString());   
                       for(Agradecimiento a : agradecimientos)
                            {
                if (a.getId() == idAgradecimiento)
                {
                    if(!a.getPersonalizada()){
                       txtAgra.setText(a.getMensaje());
                      
                    }else{
                        
                      txtAgra.setText(nombreArchivoAgradecimiento);
                       
                    }
                  agradecimiento=a;
                }
            } 
            int idCliente = cliente.getId();
            if(idCliente<=0){
                
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloContrato")
                , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("SeleccionElemento"), JOptionPane.INFORMATION_MESSAGE);

             return;   
            }
          if(ContratoClienteNegocio.Guardar(idContrato, 
                  idCliente,
                  Integer.parseInt(txtFolio.getText()),modelo.getId(),rbReconocimiento.isSelected() ,rbTitulo.isSelected(),agradecimiento.getId(),txtAgra.getText(),
                  dirigido,rbFotoPanoramica.isSelected(),rbFotoPersonalizada.isSelected(),rbFotoMisa.isSelected(),rbFotoEstudio.isSelected(),anillo,rbRentaToga.isSelected(),
                  rbMisa.isSelected(),rbBaile.isSelected(),Integer.parseInt(spMesaExtra.getValue().toString()), Integer.parseInt(spFotosExtra.getValue().toString()),rbTriptico.isSelected(),
                  Double.parseDouble(txtPrecio.getText()), dateEntregaPaquete.getDate(),dateEntregaDatos.getDate(),dateLimitePago.getDate(), nombreArchivo,
                  dateFechaContrato.getDate(), txtComentarios.getText().trim(), Program.idUsuario)){
                  this.DialogResult = true;
                  this.dispose();

               
           JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ContratoAgregado")
                            , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloContrato"), JOptionPane.INFORMATION_MESSAGE); 
                      
           }else{
                 JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);

          }
          }else{
                
                
            modelo.setId(Integer.parseInt(comboModelo.getSelectedValue().toString()));
            modelo.setImagen(comboModelo.getSelectedValue().toString());
            modelo.setNombre(comboModelo.getSelectedValue().toString());      
            
            anillo.setG(Double.parseDouble(txtGramos.getText()));
            anillo.setK(Double.parseDouble(txtKilates.getText()));
            metal.setId(Integer.parseInt(comboMaterial.getSelectedValue().toString()));
            anillo.setMetal(metal);
            
               int combo = comboDirigido.getSelectedIndex();
            switch(combo){
                case 0: dirigido = "A mis padres"; break;
                case 1: dirigido = "A mi familia"; break;
                case 2: dirigido = txtDirigido.getText(); break;
                    
            }
                        
            int idAgradecimiento = Integer.parseInt(comboAgradecimiento.getSelectedValue().toString());   
                       for(Agradecimiento a : agradecimientos)
                            {
                if (a.getId() == idAgradecimiento)
                {
                    if(!a.getPersonalizada()){
                       txtAgra.setText(a.getMensaje());
                      
                    }else{
                        
                      txtAgra.setText(nombreArchivoAgradecimiento);
                       
                    }
                  agradecimiento=a;
                }
            } 
            int idCliente = cliente.getId();
            if(idCliente<=0){
                
                JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("SeleccionElemento")
                , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloCliente"), JOptionPane.INFORMATION_MESSAGE);

             return;   
            }
                //Editar un Contrato Cliente
                if(ContratoClienteNegocio.Editar(id,
                  idCliente,
                  Integer.parseInt(txtFolio.getText()),modelo.getId(),rbReconocimiento.isSelected() ,rbTitulo.isSelected(),agradecimiento.getId(),txtAgra.getText(),
                  dirigido,rbFotoPanoramica.isSelected(),rbFotoPanoramica.isSelected(),rbFotoMisa.isSelected(),rbFotoEstudio.isSelected(),anillo,rbRentaToga.isSelected(),
                  rbMisa.isSelected(),rbBaile.isSelected(),Integer.parseInt(spMesaExtra.getValue().toString()), Integer.parseInt(spFotosExtra.getValue().toString()),rbTriptico.isSelected(),
                  Double.parseDouble(txtPrecio.getText()), dateEntregaPaquete.getDate(),dateEntregaDatos.getDate(),dateLimitePago.getDate(), nombreArchivo,
                  dateFechaContrato.getDate(), txtComentarios.getText().trim())){
                      this.DialogResult = true;
                        this.dispose();
                      JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ContratoEditado")
                            , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloContrato"), JOptionPane.INFORMATION_MESSAGE); 
          
                }else{
                      JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                , ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);

                }
                
            }
                
        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
     }
             
            
        
    }//GEN-LAST:event_btnAceptarActionPerformed
        JFileChooser fc = null;
        String rutaArchivo = null;
        String nombreArchivo = null;
    private void btnAgregarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarImagenActionPerformed
        // TODO add your handling code here:
        try
        {
            if (fc == null) {
                fc = new JFileChooser();

                //Add a custom file filter and disable the default
                //(Accept All) file filter.
                fc.addChoosableFileFilter(new ImageFilter());
                fc.setAcceptAllFileFilterUsed(false);

                //Add custom icons for file types.
                fc.setFileView(new ImageFileView());

                //Add the preview pane.
                fc.setAccessory(new ImagePreview(fc));
            }

            //Show it.
            int returnVal = fc.showDialog(this, "Buscar");

            //Process the results.
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                //TODO something with the name from the fil using file.getName()
                ImageIcon icon = new ImageIcon(((new ImageIcon(file.getPath())).getImage())
                    .getScaledInstance(297, 233, java.awt.Image.SCALE_SMOOTH));
                imgFoto.setIcon(icon);
                rutaArchivo = file.getPath();
                nombreArchivo = file.getName();
            }
        }
       catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
 
        }
        finally
        {
            //Reset the file chooser for the next time it's shown.
            fc.setSelectedFile(null);
        }
    }//GEN-LAST:event_btnAgregarImagenActionPerformed

    private void btnRetirarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarImagenActionPerformed
        // TODO add your handling code here:
        imgFoto.setIcon(null);
        rutaArchivo = null;
        nombreArchivo = null;
    }//GEN-LAST:event_btnRetirarImagenActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         if(editar){
            cargarEdicion();
         }
        try
        {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Contrato entidad = ContratoNegocio.ObtenerDetalle(idContrato);
            
            if(entidad != null){
                txtEscuela.setText(entidad.getEscuela().getNombre());
                txtEspecialidad.setText(entidad.getEspecialidad().getNombre());
                txtGeneracion.setText(entidad.getGeneracion());
                
            }
        }
        catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
     }
        finally
        {
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        try
        {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            JDialogAgregarCliente cliente = new JDialogAgregarCliente(null, true);
            cliente.setVisible(true);
            if(cliente.DialogResult)
            {
                
                cargarCliente(ClienteNegocio.Obtener(cliente.id));
            }
        }
        catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
        }finally{
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

        }
        
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        try
        {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            JDialogBuscarCliente cliente = new JDialogBuscarCliente(null, true);
            cliente.setVisible(true);
            if(cliente.DialogResult)
            {
                
                cargarCliente(cliente.cliente);
            }
        }
        catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
    }finally{
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();        
        if(((car < '0') || (car > '9'))&& (car !='.'))evt.consume();{
    }                                    
    if (car == '.' && txtPrecio.getText().contains(".")) { evt.consume(); }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtFolioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFolioKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();        
        if(((car < '0') || (car > '9')))evt.consume();{
    }                                    
  
    }//GEN-LAST:event_txtFolioKeyTyped

    private void txtKilatesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKilatesKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();        
        if(((car < '0') || (car > '9'))&& (car !='.'))evt.consume();{
    }                                    
    if (car == '.' && txtKilates.getText().contains(".")) { evt.consume(); }
    }//GEN-LAST:event_txtKilatesKeyTyped

    private void txtGramosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGramosKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();        
        if(((car < '0') || (car > '9'))&& (car !='.'))evt.consume();{
    }                                    
    if (car == '.' && txtGramos.getText().contains(".")) { evt.consume(); }
    }//GEN-LAST:event_txtGramosKeyTyped

    private void comboDirigidoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDirigidoItemStateChanged
        // TODO add your handling code here:
           if(comboDirigido.getSelectedIndex()==2){
            txtDirigido.setEditable(true);
            txtDirigido.setEnabled(true);
        }else{
             txtDirigido.setEditable(false);
             txtDirigido.setEnabled(false);
        }
    }//GEN-LAST:event_comboDirigidoItemStateChanged
        
        JFileChooser fcD = null;
        String rutaArchivoD = null;
        String nombreArchivoAgradecimiento = null;
    private void btnAdjuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdjuntarActionPerformed
        // TODO add your handling code here:
         try
        {
            if (fcD == null) {
                fcD = new JFileChooser();

                //Add a custom file filter and disable the default
                //(Accept All) file filter.
                
                fcD.setAcceptAllFileFilterUsed(true);
                }

            //Show it.
            int returnVal = fcD.showDialog(this, "Buscar");

            //Process the results.
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fcD.getSelectedFile();
                //TODO something with the name from the fil using file.getName()
                
                rutaArchivoD = file.getPath();
                nombreArchivoAgradecimiento = file.getName();
                txtAgra.setText(nombreArchivoAgradecimiento);
                }
        }
        catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
 

        }
        finally
        {
            //Reset the file chooser for the next time it's shown.
            fcD.setSelectedFile(null);
        }
        
    }//GEN-LAST:event_btnAdjuntarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
         txtAgra.setText(null);
        rutaArchivoD = null;
        nombreArchivoAgradecimiento = null;
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void comboAgradecimientoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboAgradecimientoItemStateChanged
        // TODO add your handling code here:
        if(comboAgradecimiento.getSelectedIndex()==0){
            txtAgra.setText(null);
            txtAgra.setEnabled(true);
            btnRemover.setEnabled(true);
            btnAdjuntar.setEnabled(true);
        }
        else{
            txtAgra.setText(null);
            txtAgra.setEnabled(false);
            btnRemover.setEnabled(false);
            btnAdjuntar.setEnabled(false);
        }
    }//GEN-LAST:event_comboAgradecimientoItemStateChanged
        JFileChooser fcA = null;
        String rutaArchivoA = null;
        String nombreArchivoA = null;    
    private void cargarCliente(Cliente cliente)
    {
        try
        {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));  
            this.cliente = cliente;
            txtNombre.setText(cliente.getNombre());
            txtTelefono.setText(cliente.getTelefono());
            txtCelular.setText(cliente.getCelular());
            txtCorreo.setText(cliente.getCorreo());
            txtDireccion.setText(cliente.getDireccion().toString());
        }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
 
            
        }
        finally
        {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAdjuntar;
    private javax.swing.JButton btnAgregarImagen;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnRetirarImagen;
    private gdm.presentacion.CustomComboBox comboAgradecimiento;
    private javax.swing.JComboBox comboDirigido;
    private gdm.presentacion.CustomComboBox comboMaterial;
    private gdm.presentacion.CustomComboBox comboModelo;
    private org.jdesktop.swingx.JXDatePicker dateEntregaDatos;
    private org.jdesktop.swingx.JXDatePicker dateEntregaPaquete;
    private org.jdesktop.swingx.JXDatePicker dateFechaContrato;
    private org.jdesktop.swingx.JXDatePicker dateLimitePago;
    private javax.swing.JLabel imgFoto;
    private javax.swing.JLabel imgModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JRadioButton rbBaile;
    private javax.swing.JRadioButton rbFotoEstudio;
    private javax.swing.JRadioButton rbFotoMisa;
    private javax.swing.JRadioButton rbFotoPanoramica;
    private javax.swing.JRadioButton rbFotoPersonalizada;
    private javax.swing.JRadioButton rbMisa;
    private javax.swing.JRadioButton rbReconocimiento;
    private javax.swing.JRadioButton rbRentaToga;
    private javax.swing.JRadioButton rbTitulo;
    private javax.swing.JRadioButton rbTriptico;
    private javax.swing.JSpinner spFotosExtra;
    private javax.swing.JSpinner spMesaExtra;
    private javax.swing.JLabel txtAgra;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextArea txtComentarios;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDirigido;
    private javax.swing.JTextField txtEscuela;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtGeneracion;
    private javax.swing.JTextField txtGramos;
    private javax.swing.JTextField txtKilates;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void cargarEdicion() {
         try{
                   
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        ContratoCliente contrato =ContratoClienteNegocio.Obtener(id);         
        if(contrato != null){
            
            if(contrato.getCliente() != null){
            cliente = contrato.getCliente();
            txtNombre.setText(contrato.getCliente().getNombre());
            txtTelefono.setText(contrato.getCliente().getTelefono());
            txtCelular.setText(contrato.getCliente().getCelular());
            txtCorreo.setText(contrato.getCliente().getCorreo());
            txtDireccion.setText(contrato.getCliente().getDireccion().toString());
                
            }
            comboModelo.setSelectedValue(contrato.getModelo().getId());
            txtPrecio.setText(String.valueOf(contrato.getPrecio()));
            dateFechaContrato.setDate(contrato.getFechaContrato());
            txtFolio.setText(String.valueOf(contrato.getFolio()));
            rbTriptico.setSelected(contrato.isTriptico());
            rbTitulo.setSelected(contrato.isTitulo());
            rbReconocimiento.setSelected(contrato.isReconocimiento());
            comboAgradecimiento.setSelectedValue(contrato.getAgradecimiento().getId());            
            txtAgra.setText(contrato.getMensaje());                      
//            txtAgradecimiento.setText(contrato.getAgradecimiento().getMensaje());
            comboDirigido.setSelectedItem(contrato.getDirigido());
            rbRentaToga.setSelected(contrato.isRentaToga());
            rbMisa.setSelected(contrato.isMisa());
            rbBaile.setSelected(contrato.isBaile());
            spFotosExtra.setValue(contrato.getFotosExtra());
            spMesaExtra.setValue(contrato.getMesaExtra());
            rbFotoPanoramica.setSelected(contrato.getFotoPanoramica());
            rbFotoPersonalizada.setSelected(contrato.isFotoPersonalizada());
            rbMisa.setSelected(contrato.isMisa());
            rbBaile.setSelected(contrato.isBaile());
            rbFotoEstudio.setSelected(contrato.isFotoEstudio());                              
            comboMaterial.setSelectedValue(contrato.getAnillo().getMetal().getId());
            txtKilates.setText(String.valueOf(contrato.getAnillo().getK()));
            txtGramos.setText(String.valueOf(contrato.getAnillo().getG()));
            txtComentarios.setText(contrato.getComentarios());
            dateEntregaDatos.setDate(contrato.getFechaEntregaDatos());
            dateEntregaPaquete.setDate(contrato.getFechaEntregaPaquete());
            dateLimitePago.setDate(contrato.getFechaLimitePago());
            imgFoto.setText(contrato.getContratoImagen());
            
            
            
        }
     }catch(Exception ex){
       Program.logger.error(this, ex);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("ErrorMensaje")
                ,  ResourceBundle.getBundle("gdm/entidades/clases/resource").getString("TituloError"), JOptionPane.INFORMATION_MESSAGE);
        
     }
        finally{
          this.setCursor(Cursor.getDefaultCursor());     
        }   
    }
    
    
    }

